### ISSUE TITLE
[Standardization] Release Pipeline using GitHub Actions

### ISSUE THREAD

**Issue by TanmoySG** [TanmoySG/wunder-identity-provider#81]
Add Release Pipeline to make release, when tagged, using Github Actions.

As a Part of 

- [ ] #79 

[Checkpoints]

- [x] Add Pipeline with Github Actions
- [x] Trigger only on Tag

[Snippets]

A sample GH Action YML
```
name: Release on tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: softprops/action-gh-release@v1
```
